// <auto-generated />
using System;
using MedicalResearch.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalResearch.DAL.Migrations
{
    [DbContext(typeof(MedicalResearchDbContext))]
    partial class MedicalResearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("ClinicSequence");

            modelBuilder.HasSequence("ClinicStockMedicineSequence");

            modelBuilder.HasSequence("DosageFormSequence");

            modelBuilder.HasSequence("MedicineContainerSequence");

            modelBuilder.HasSequence("MedicineSequence");

            modelBuilder.HasSequence("MedicineTypeSequence");

            modelBuilder.HasSequence("PatientSequence");

            modelBuilder.HasSequence("RoleSequence");

            modelBuilder.HasSequence("SupplySequence");

            modelBuilder.HasSequence("UserSequence");

            modelBuilder.HasSequence("VisitSequence");

            modelBuilder.Entity("ClinicStockMedicineSupply", b =>
                {
                    b.Property<int>("ClinicStockMedicinesId")
                        .HasColumnType("integer");

                    b.Property<int>("SuppliesId")
                        .HasColumnType("integer");

                    b.HasKey("ClinicStockMedicinesId", "SuppliesId");

                    b.HasIndex("SuppliesId");

                    b.ToTable("ClinicStockMedicineSupply");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"ClinicSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("AddressOne")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressTwo")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clinics", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.ClinicStockMedicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"ClinicStockMedicineSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("MedicineId");

                    b.ToTable("ClinicsStockMedicines", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.DosageForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"DosageFormSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DosageForms", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "tablet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "capsule"
                        },
                        new
                        {
                            Id = 3,
                            Name = "syrup"
                        },
                        new
                        {
                            Id = 4,
                            Name = "suspension"
                        },
                        new
                        {
                            Id = 5,
                            Name = "oinment"
                        });
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"MedicineSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DosageFormId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicineContainerId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicineTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DosageFormId");

                    b.HasIndex("MedicineContainerId");

                    b.HasIndex("MedicineTypeId");

                    b.ToTable("Medicines", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.MedicineContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"MedicineContainerSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MedicinesContainers", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "box"
                        },
                        new
                        {
                            Id = 2,
                            Name = "bottle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "blister"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ampoule"
                        },
                        new
                        {
                            Id = 5,
                            Name = "vial"
                        });
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.MedicineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"MedicineTypeSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MedicinesTypes", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            Name = "D"
                        });
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"PatientSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Patients", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"RoleSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sponsor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Researcher"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"SupplySequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Supplies", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"UserSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int?>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PaswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.UseTpcMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "byklin@list.ru",
                            FirstName = "Admin",
                            Initials = "",
                            LastName = "",
                            Password = "0m5ILJlS4vE+9gsxEmgX2/KGhmeCBGyekUjYTq1/CgY=",
                            PaswordSalt = new byte[] { 93, 61, 5, 143, 108, 94, 214, 190, 104, 158, 126, 120, 116, 41, 15, 150, 148, 126, 236, 66, 236, 242, 31, 177, 156, 197, 29, 84, 196, 192, 202, 173 },
                            State = 0
                        });
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"VisitSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfVisit")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Visits", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRole");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ClinicStockMedicineSupply", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.ClinicStockMedicine", null)
                        .WithMany()
                        .HasForeignKey("ClinicStockMedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.Supply", null)
                        .WithMany()
                        .HasForeignKey("SuppliesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.ClinicStockMedicine", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.Clinic", "Clinic")
                        .WithMany("ClinicStockMedicines")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Medicine", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.DosageForm", "DosageForm")
                        .WithMany("Medicines")
                        .HasForeignKey("DosageFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.MedicineContainer", "MedicineContainer")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.MedicineType", "MedicineType")
                        .WithMany("Medicines")
                        .HasForeignKey("MedicineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DosageForm");

                    b.Navigation("MedicineContainer");

                    b.Navigation("MedicineType");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Patient", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.Clinic", "Clinic")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Supply", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.Clinic", "Clinic")
                        .WithMany("Supplies")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.Medicine", "Medicine")
                        .WithMany("Supplies")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.User", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId");

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Visit", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.Clinic", "Clinic")
                        .WithMany("Visits")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalResearch.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Medicine");

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("MedicalResearch.Domain.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_RoleId");

                    b.HasOne("MedicalResearch.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRole_UserId");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Clinic", b =>
                {
                    b.Navigation("ClinicStockMedicines");

                    b.Navigation("Patients");

                    b.Navigation("Supplies");

                    b.Navigation("Users");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.DosageForm", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Medicine", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.MedicineContainer", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.MedicineType", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("MedicalResearch.Domain.Models.Patient", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
